#!/bin/bash
set -o nounset -o errexit -o pipefail

script_dir="$(p="$0"; while true; do t="$(readlink "$p")"; cd "$(dirname "$p")"; test -z "$t" && break || p="$t"; done; pwd -P)"
seqshmig_path="$script_dir/.seqshmig"
mkdir -p "$seqshmig_path"

user="mbucc"
project="shmig"

get_latest_master_commit_sub() {
  git ls-remote "git://github.com/$user/$project.git" |
  while read commit ref
  do
    # echo "$commit - $ref" >&2
    if test "$ref" = "refs/heads/master"
    then
      echo "$commit"
    fi
  done
}

get_latest_master_commit() {
  commit="$(get_latest_master_commit_sub)"
  if test -z "$commit"
  then
    exit 1
  fi
  echo "$commit"
}

commit="$(get_latest_master_commit)"
short_commit="${commit:0:7}"
file="shmig-$short_commit"

shmig_cmd_path="$seqshmig_path/$file"
curl "https://raw.githubusercontent.com/mbucc/$project/$short_commit/shmig" > "$shmig_cmd_path"
# Remove execution permission not to run shmig command directly
chmod -x "$shmig_cmd_path"
echo "$short_commit" > "$seqshmig_path/shmig-latest-commit"
