#!/bin/bash
set -o nounset -o errexit -o pipefail

# 1st is the one you have created with last “create”
put_2nd_latest_script_seq() {
  local second_latest="$(
    dir="$1"
    ls "$dir" |
    sort -nr |
    sed -n -e '2,2 p'
  )"
  if test -z "$second_latest"
  then
    echo 0
  else
    echo "$second_latest" | sed -e 's/-.*//'
  fi
}

commit_file=".shmig-latest-commit"

if ! test -r "$commit_file"
then
  ./fetch-latest-shmig
fi

bash ".shmig-$(cat "$commit_file")" "$@" |
while IFS= read line
do
  if grep -q "^generated " <<< "$line"
  then
    script_path="$(sed -e 's/^generated //' <<< "$line")"
    migrations_dir="$(dirname "$script_path")"
    filename="$(basename "$script_path")"
    latest_script_seq="$(put_2nd_latest_script_seq "$migrations_dir")"
    next_script_seq=$(($latest_script_seq + 1))
    new_script_path="$migrations_dir/$next_script_seq-script.sql"
    mv "$script_path" "$new_script_path"
    echo "generated $new_script_path"
  else
    echo "$line"
  fi
done
